---
- name: Configuration des équipements réseau
  hosts: all
  become: yes
  tasks:
    - name: Mise à jour du système sur le routeur et les switches
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Configuration des adresses IP sur les interfaces des PC
      ansible.builtin.network:
        name: "{{ item.interface }}"
        ipv4: "{{ item.ip_address }}"
        netmask: "{{ item.netmask }}"
        state: up
      with_items:
        - {
            interface: "eth0",
            ip_address: "192.168.1.2",
            netmask: "255.255.255.0",
          }
        - {
            interface: "eth0",
            ip_address: "192.168.1.3",
            netmask: "255.255.255.0",
          }
        - {
            interface: "eth0",
            ip_address: "192.168.1.4",
            netmask: "255.255.255.0",
          }
      when: inventory_hostname in ['PC1', 'PC2', 'PC3']

    - name: Configuration des VLANs sur le switch
      cisco.ios.ios_vlan:
        vlan_id: 10
        name: "VLAN_10"
        state: present
      when: inventory_hostname == 'switch'

    - name: Configuration de l'interface VLAN sur le switch
      cisco.ios.ios_interface:
        name: "Vlan10"
        vlan_id: 10
        ipv4: "192.168.10.1"
        netmask: "255.255.255.0"
        state: up
      when: inventory_hostname == 'switch'

    - name: Configuration de l'interface du routeur
      cisco.ios.ios_interface:
        name: "GigabitEthernet0/0"
        ipv4: "192.168.10.254"
        netmask: "255.255.255.0"
        state: up
      when: inventory_hostname == 'routeur'

    - name: Activation du routage sur le routeur
      cisco.ios.ios_routing:
        router_bgp:
          asn: 65001
          networks:
            - "192.168.10.0/24"
      when: inventory_hostname == 'routeur'

    - name: Configuration du route statique sur le routeur
      cisco.ios.ios_static_route:
        network: "0.0.0.0"
        netmask: "0.0.0.0"
        next_hop: "192.168.10.254"
      when: inventory_hostname == 'routeur'

    - name: Configuration du routeur par défaut sur les PC
      ansible.builtin.command:
        cmd: "ip route add default via 192.168.10.254"
      when: inventory_hostname in ['PC1', 'PC2', 'PC3']
