become: true
hosts: all
name: Configuration des équipements réseau
tasks:
- apt:
    update_cache: true
    upgrade: 'yes'
  name: Mise à jour du système sur le routeur et les switches
  when: ansible_facts['os_family'] == 'Debian'
- ansible.builtin.network:
    ipv4: '{{ item.ip_address }}'
    name: '{{ item.interface }}'
    netmask: '{{ item.netmask }}'
    state: up
  name: Configuration des adresses IP sur les interfaces des PC
  when: inventory_hostname in ['PC1', 'PC2', 'PC3']
  with_items:
  - interface: eth0
    ip_address: 192.168.1.2
    netmask: 255.255.255.0
- cisco.ios.ios_vlan:
    name: VLAN_10
    state: present
    vlan_id: 10
  name: Configuration des VLANs sur le switch
  when: inventory_hostname == 'switch'
- cisco.ios.ios_interface:
    ipv4: 192.168.10.1
    name: Vlan10
    netmask: 255.255.255.0
    state: up
    vlan_id: 10
  name: Configuration de l'interface VLAN sur le switch
  when: inventory_hostname == 'switch'
- cisco.ios.ios_interface:
    ipv4: 192.168.10.254
    name: GigabitEthernet0/0
    netmask: 255.255.255.0
    state: up
  name: Configuration de l'interface du routeur
  when: inventory_hostname == 'routeur'
- cisco.ios.ios_routing:
    router_bgp:
      asn: 65001
      networks:
      - 192.168.10.0/24
  name: Activation du routage sur le routeur
  when: inventory_hostname == 'routeur'
- cisco.ios.ios_static_route:
    netmask: 0.0.0.0
    network: 0.0.0.0
    next_hop: 192.168.10.254
  name: Configuration du route statique sur le routeur
  when: inventory_hostname == 'routeur'
- block:
  - name: Configurer les règles de pare-feu
    shell: stormshield set firewall rules
  - name: Activer la sécurité avancée
    shell: stormshield enable advanced-security
  name: Configurer le Stormshield
